<!DOCTYPE html>
<html>
    <head>
        <title>About</title>
        <link href="/assets/styles/main.css" type="text/css" rel="stylesheet"/>
        <link href="/assets/styles/sidebar.css" type="text/css" rel="stylesheet"/>
    </head>
    <body>
        <section class="content">
            + render ./views/sidebar/sidebar.tl +

            <main>
                <h1>About</h1>
            </main>
        </section>

        <script src="/assets/js/main.js"></script>
        <script src="/assets/js/sidebar.js"></script>
    </body>
</html>